import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst } from 'workbox-strategies';

// Clean up old caches
cleanupOutdatedCaches();

// Precache all the files generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Define offline route mapping
const offlineRoutes = {
    '/dashboard': '/offline/dashboard.html',
    '/courses': '/offline/courses.html', 
    '/profile': '/offline/profile.html'
};

// Cache static assets (CSS, JS, images)
registerRoute(
    ({ request }) => 
        request.destination === 'style' || 
        request.destination === 'script' || 
        request.destination === 'image',
    new CacheFirst({
        cacheName: 'static-assets',
        plugins: [{
            cacheKeyWillBeUsed: async ({ request }) => {
                return new URL(request.url).href;
            }
        }]
    })
);

// Listen for skip waiting
self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'SKIP_WAITING') {
        self.skipWaiting();
    }
});

// Main fetch event handler
self.addEventListener('fetch', (event) => {
    const request = event.request;
    const url = new URL(request.url);
    
    // Skip non-HTTP requests
    if (!url.protocol.startsWith('http')) return;
    
    // Handle Inertia.js XHR requests
    if (request.headers.get('X-Inertia') || 
        request.headers.get('X-Requested-With') === 'XMLHttpRequest') {
        
        event.respondWith(
            fetch(request)
                .catch(async () => {
                    console.log('🔄 Inertia request failed, serving offline page');
                    
                    // Get the offline page for this route
                    const pathname = url.pathname;
                    const offlinePage = offlineRoutes[pathname] || '/offline/dashboard.html';
                    
                    // Force a full page reload to the offline page
                    return new Response('', {
                        status: 409, // Conflict - tells Inertia to do a full page reload
                        headers: {
                            'X-Inertia-Location': offlinePage
                        }
                    });
                })
        );
        return;
    }
    
    // Handle regular navigation requests
    if (request.mode === 'navigate') {
        event.respondWith(
            fetch(request)
                .catch(async () => {
                    console.log('🔄 Navigation failed, serving offline fallback');
                    
                    const pathname = url.pathname;
                    const offlinePage = offlineRoutes[pathname];
                    
                    if (offlinePage) {
                        // Try to get from cache first
                        try {
                            const cache = await caches.open('offline-pages');
                            const cachedResponse = await cache.match(offlinePage);
                            if (cachedResponse) {
                                return cachedResponse;
                            }
                        } catch (e) {
                            console.log('Cache miss for offline page');
                        }
                        
                        // Fallback to fetch the offline page
                        try {
                            const offlineResponse = await fetch(offlinePage);
                            return offlineResponse;
                        } catch (e) {
                            console.log('Failed to fetch offline page');
                        }
                    }
                    
                    // Ultimate fallback
                    return new Response(`
                        <!DOCTYPE html>
                        <html>
                        <head>
                            <title>Offline - Kelas Sarah</title>
                            <meta charset="utf-8">
                            <meta name="viewport" content="width=device-width, initial-scale=1">
                            <script src="https://cdn.tailwindcss.com"></script>
                        </head>
                        <body class="bg-gray-100 min-h-screen flex items-center justify-center">
                            <div class="text-center p-8">
                                <div class="mb-6">
                                    <svg class="w-16 h-16 mx-auto text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M18.364 5.636l-3.536 3.536m0 5.656l3.536 3.536M9.172 9.172L5.636 5.636m3.536 9.192L5.636 18.364M12 2v4m0 12v4m10-10h-4m-12 0H2"></path>
                                    </svg>
                                </div>
                                <h1 class="text-2xl font-bold text-gray-800 mb-4">Sedang Offline</h1>
                                <p class="text-gray-600 mb-6">Tidak dapat terhubung ke internet. Silakan periksa koneksi Anda.</p>
                                <button onclick="window.location.reload()" 
                                        class="bg-blue-500 hover:bg-blue-600 text-white px-6 py-3 rounded-lg font-medium transition-colors">
                                    Coba Lagi
                                </button>
                            </div>
                        </body>
                        </html>
                    `, {
                        status: 503,
                        headers: { 'Content-Type': 'text/html' }
                    });
                })
        );
    }
});

// Preload offline pages into cache
self.addEventListener('activate', (event) => {
    event.waitUntil(
        caches.open('offline-pages').then(cache => {
            return Promise.all(
                Object.values(offlineRoutes).map(url => {
                    return cache.add(url).catch(err => {
                        console.log(`Failed to cache ${url}:`, err);
                    });
                })
            );
        })
    );
});